### ISSUE TITLE
Sagui explodes on `npm install sagui` without explanation

### ISSUE THREAD

**Issue by ticolucci** [saguijs/sagui#349] opened 2017-05-11 10:17 UTC
While trying to install sagui in the bellow folder structure, the post-install script exits with 1 (failure) without logging the reason.

Apparently, the root cause is the `package.json` is not owned by the user running the post-script.

I would like sagui to explain this on this failure =)

Details:
```bash
[le_user@0d16cc72b78d client]$ yarn install # with package.json containing sagui as a dependency
...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[3/3] ⡀ sagui
[-/3] ⡀ waiting...
[-/3] ⡀ waiting...
[-/3] ⡀ waiting...
error /opt/project/client/node_modules/sagui: Command failed.
Exit code: 1
Command: sh
Arguments: -c node ./bin/sagui.js install
Directory: /opt/project/client/node_modules/sagui
Output:
🐵  Sagui Failed to install Sagui files in the project.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[le_user@0d16cc72b78d client]$ ls -la .
total 276
drwxr-xr-x   3 le_user le_user   4096 May 11 10:12 .
drwx------  12 le_user le_user   4096 May 11 10:12 ..
-rw-r--r--   1 root    root        25 May 10 13:38 .eslintrc
-rw-r--r--   1 root    root        69 May  2 11:06 .npmrc
drwxrwxr-x 858 le_user le_user  32768 May 11 10:12 node_modules
-rw-r--r--   1 root    root      1291 May 10 13:38 package.json
-rw-r--r--   1 root    root      1267 May 10 13:50 sagui.config.js
-rw-r--r--   1 root    root    217524 May  8 14:59 yarn.lock
[le_user@0d16cc72b78d client]$ node node_modules/sagui/bin/sagui.js install
🐵  Sagui Failed to install Sagui files in the project.
[le_user@0d16cc72b78d client]$ echo $?
1
[le_user@0d16cc72b78d client]$ 
```

**Comment by pirelenito** [comment] 2017-05-11 11:02
Thanks for submitting! We need to improve the error message.

**Comment by pirelenito** [comment] 2017-06-27 07:48
Closing this, since #350 fixed the root cause.

**Closed by pirelenito** 2017-06-27 07:48 UTC
