### ISSUE TITLE
Source maps still not working

### ISSUE THREAD

**Issue by zsherman** [saguijs/sagui#284] opened 2016-12-15 22:38 UTC
I see that an attempt to fix source maps in dev was merged here https://github.com/saguijs/sagui/pull/277 but they are still not working for me out of the box.

**Comment by xaviervia** [comment] 2016-12-19 17:03
Hi! Sorry that it took so long for us to answer on this.

There seems to be an ongoing issue with this. What is the setup in which is not working? Is it for both tests and development?

Thanks!

**Comment by pirelenito** [comment] 2017-04-14 19:51
I've tried again with the upcoming [v9](https://github.com/saguijs/sagui/tree/v9) release and it looks like it is working.

You can try it with `npm install --save-dev sagui@beta`.

I'm closing the issue. Let me know if you can still reproduce it and we can re-open it.

**Closed by pirelenito** 2017-04-14 19:51 UTC
