### ISSUE TITLE
Dev Server does not work with React-Router

### ISSUE THREAD

**Issue by karthikiyengar** [saguijs/sagui#270] opened 2016-10-28 20:22 UTC
The bundle that webpack dev server generates is fetched from a relative path. This would break react router with browserHistory. An example follows.

```
import React from 'react'
import ReactDOM from 'react-dom'
import { Route, Router, browserHistory } from 'react-router'

const App = (props) => {
  return (
    <div>
      <span>This is a top level route</span>
    </div>
  )
}

const NestedApp = (props) => {
  return (
    <div>
      <span>This is a nested app</span>
    </div>
  )
}

ReactDOM.render(
  <Router history={browserHistory}>
    <Route path='/' component={App} />
    <Route path='/nested/app' component={NestedApp} />
  </Router>,
document.querySelector('#root'))
```

This results in a call to the following address for the bundle: http://localhost:3000/nested/index-f6a3af876611b2b52b20.js causing the rendering to fail.

Currently using hashHistory to get around it. Ideally, the webpack bundle should always be fetched from the publicPath at which it has been generated (root in this case, since none has been set) in the index.html file.

**Comment by xaviervia** [comment] 2016-10-29 15:25
OK, I was able to reproduce with the example. I was also able to verify that setting the `publicPath` to `/` solves the problem, as you said.

Setting the publicPath as a fixed value is probably not convenient for most cases, since it will mean, for example, that publishing in GitHub pages under a certain path will not work unless you specify the same path in the Sagui config, which feels to me unnecessary. Instead, I'm thinking about allowing a publicPath to be specified in the `page` configuration. 

The `sagui.config.js` for your example would then look like this:

```javascript
/**
 * Sagui configuration object
 * see: http://sagui.js.org/
 */
module.exports = {
  pages: {
    entries: ['index'],
    publicPath: '/'
  }
}
```

I’m not sure about the names.

What do you think? I made this as a work in progress pull request:
https://github.com/saguijs/sagui/pull/271

**Comment by karthikiyengar** [comment] 2016-10-29 18:56
Well, I did manage to get it working by using the webpack.output.publicPath as @pirelenito mentioned. I think a note in the docs regarding use cases with router/pages not mounted at root would suffice - in line with the minimalism and not having too many configuration options.

**Comment by xaviervia** [comment] 2016-10-29 20:47
OK, @pirelenito is also on board with only changing the documentation, since configuring webpack is simple and works. 

We will discuss later whether or not to add a default option and how to handle these cases. I’ll close this issue, we can continue in the PR. Thanks!

**Closed by xaviervia** 2016-10-29 20:47 UTC
